services:
  iot-postgres:
    image: postgres:16-alpine
    container_name: luminary-iot-pg
    environment:
      POSTGRES_USER: iot
      POSTGRES_PASSWORD: iot_dev_password
      POSTGRES_DB: iot_core
    ports:
      - "5434:5432"
    volumes:
      - luminary_iot_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iot -d iot_core"]
      interval: 5s
      timeout: 5s
      retries: 10

  iot-redis:
    image: redis:7-alpine
    container_name: luminary-iot-redis
    ports:
      - "6381:6379"

  iot-mqtt:
    image: eclipse-mosquitto:2
    container_name: luminary-iot-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

volumes:
  luminary_iot_pg:
